M48
; DRILL file {KiCad 9.0.6} date 2025-12-27T23:01:51-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-27T23:01:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X137.6Y-80.11
X137.6Y-85.89
T2
X137.0Y-135.0
X184.0Y-79.0
X195.0Y-135.0
M30
